### ISSUE TITLE
一个小小建议，

### ISSUE THREAD

**Issue by Tiexcn** [LeeJiangWei/pcr-calculator#2]
可以在扩展上 加入图书管 https://pcredivewiki.tw/Armory 直达连接按钮 就舒服了

**Comment by LeeJiangWei** [comment]
好的，会考虑加入当前页面不是图书馆时，让弹出窗口显示图书馆的直达按钮

**Comment by LeeJiangWei** [comment]
让扩展非目标页面具有不同的弹出窗有点难搞，建议直接把图书馆加入自己的书签栏
