### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by mzzzzzl** [LeeJiangWei/pcr-calculator#3]
感谢作者。
因为掉落概率的问题，并不能保证正好刷够这么多装备。
能不能实现这么一个功能
如果规划中装备A仅在B图掉落，增加一个停止条件：B图装备A掉落XX件后停止。
这样把某几件装备刷完之后再重新规划一下，能更好的利用体力。
再次感谢

**Comment by LeeJiangWei** [comment]
这个恐怕不太可行：
1. 装备的掉落是直接根据概率乘算的期望值，并不是模拟随机。如果在实际刷图中出现了实际掉落与期望相差太大的情况，不是程序能够判断出来的，可能需要手动调整人物装备后再重新解析并计算。
2. 另外，由于线性规划是极优的，算法已经保证了你不会浪费太多的体力在多出的装备上。（如果是整数规划，那就是最优的了。）
3. 最后也是最重要的一点，计算过程是调用的外部的实现，我并不能很轻易地去修改里面的逻辑，所以有关计算细节的建议可能都没很好的办法能解决。
