### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by ko2o30000** [LeeJiangWei/pcr-calculator#4]
感谢作者。十分喜欢这个工具。

关于谷歌应用商店上架的问题，可以考虑上架chromium版edge的商店，目测开发者账户并不收费。而且chrome的插件可以直接移植。

目前pcr刷图规划的同类工具几乎没有，如果能把这个项目完善，稍加宣传用户群必然庞大。
提一点可能的发展方向。
1、做成独立的页面，从图书馆获取数据，而不再外挂于图书馆。
2、加入角色、库存图片识别。
3、这两个方向实现之后，此工具的便利性会吸引大量用户，可以考虑在页面适当中加入商业广告，我觉得盈利前景应该还可以。

这些想法来自于一个类似的工具——明日方舟工具箱。（https://gachasalt.github.io/ArkToolDemo/#/）
类似的功能非常完善。不过这个作者并没有往盈利方向去，而是单纯的因为爱！
不知对你是否有参考价值。如果需要的话，我可以帮你联系这个工具的作者。

咕噜灵波（●′∀‵）ノ♡

**Comment by LeeJiangWei** [comment]
### 感谢你的提议，承蒙厚爱，不胜感激。
+ 关于应用商店的问题，实际上我已经注册好了开发者账号，不过之前因为一些奇怪的原因审核没有通过，最近有空我会再尝试一下，edge那边我也会试试。
+ 关于独立页面，在不久前已经有更好的工具出现，我就不再重复造轮子了，这里贴出链接：
   + 独立页面的素材规划：[公主连结素材规划国服](https://v01d.gitee.io/pcrtool/)
   + 国服资料站：[真步真步视界术](https://mahomaho-insight.info/)
+ 关于角色、库存的图片识别，这并不是一项容易实现的工作，我目前的水平还不够；以后可能会，也可能不会考虑这方面的开发，所以很抱歉，没能满足你的期待。
+ 因为没有维护服务器的支出，也因为自己做的并不算很好，我不会（也不好意思）往盈利方面想，对我项目的star就是对我很好的肯定和鼓励了。

最后再次感谢你的建议，如果还有什么建议或想法，也欢迎继续留言。
