### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by qinyangyangyu** [LeeJiangWei/pcr-calculator#5]
因为在刷大量装备的时候，通常应该是从高地图刷到低地图比较合理，因为很可能会因为高级装备刷的出货期望偏低了，而导致刷到很多低级装备，造成“**先刷低级装备”出现浪费体力的情况**。所以建议添加一个**地图从高到低显示**的功能。这个功能应该排序下就行了把，可以看的方便一点，不用从下往上看，谢谢。

**Comment by qinyangyangyu** [comment]
可能会由于高级装备比期望多刷了很多次，连带导致多刷了低级装备，可能导致溢出浪费体力。

**Comment by qinyangyangyu** [comment]
顺便推荐把总耗体力量放到第一行

**Comment by LeeJiangWei** [comment]
已收到，谢谢你的建议，近期有空就会开始着手搞

**Comment by LeeJiangWei** [comment]
本来想实现一个点击表头排序的，后来觉得太麻烦，目前是按地图从大到小排序了
